app:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    sslmode: require

  flyway:
    enabled: true
    locations: classpath:db/migration